#!/bin/bash

#You may need to install gunicorn first by running
#pip install gunicorn 
#This is nice beceuse it's self-contained if you use a virtualenv.

# -w is the number of workers, generally 2N+1 where N is the number of CPUs
# -b is the ip:port to bind to
gunicorn -w 9 -b 127.0.0.1:12345 life_webapp:app
